---
services:
  mirakurun:
    container_name: mirakurun
    image: m1u7aku/softcas-mirakurun:latest-amd64
#    build:
#      context: "./mirakurun"
#      dockerfile: "Dockerfile"
    privileged: true
    ports:
      - "40772:40772"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mirakurun/conf:/usr/local/etc/mirakurun
      - ./mirakurun/softcas/libpcsclite.so.1.0.0:/usr/lib/libpcsclite.so.1.0.0
      - mirakurun-db:/usr/local/var/db/mirakurun
    devices:
      - /dev/bus:/dev/bus
      - /dev/dvb:/dev/dvb
    environment:
      TZ: Asia/Tokyo
    restart: always
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

networks:
  default:
    name: rec_server
volumes:
  mirakurun-db:
    driver_opts:
      type: cifs
      o: 'username=__CIFS_USER__,password=__CIFS_PASSWORD__'
      device: "//__CIFS_HOST__/mirakurun-db"
