version: '2'
services:
  # mirakurun
  mirakurun:
    container_name: mirakurun
    build:
      context: ./mirakurun
      dockerfile: "Dockerfile"
    privileged: true
    ports:
      - "40772:40772"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mirakurun/conf:/usr/local/etc/mirakurun
      - ./mirakurun/db:/usr/local/var/db/mirakurun
    devices:
      - /dev/bus:/dev/bus
      - /dev/dvb:/dev/dvb
    environment:
      TZ: Asia/Tokyo
    restart: always

  # mysql
  mysql:
    container_name: mariadb
    image: mariadb:10.5
    #image: mysql:8.0 # 囲み文字を使用する場合
    volumes:
      - ./mysql-db:/var/lib/mysql
    environment:
      MYSQL_USER: epgstation
      MYSQL_PASSWORD: epgstation
      MYSQL_ROOT_PASSWORD: epgstation
      MYSQL_DATABASE: epgstation
      TZ: "Asia/Tokyo"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --performance-schema=false --expire_logs_days=1 # for mariadb
    #command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_as_ci --performance-schema=false --expire_logs_days=1 --default-authentication-plugin=mysql_native_password # for myql
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # epgstation
  epgstation:
    container_name: epgstation
    build:
      context: "./epgstation"
      dockerfile: "Dockerfile"
    volumes:
      - ./epgstation/config:/app/config
      - ./epgstation/data:/app/data
      - ./epgstation/logs:/app/logs
      - ./epgstation/recordedTmp:/app/recordedTmp
      - /volume1/video/recorded:/app/recorded
      - /volume1/video/thumbnail:/app/thumbnail
      - /var/run:/var/run
    privileged: true
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - mirakurun
      - mysql
    ports:
      - "8888:8888"
      - "8889:8889"
#     user: "1000:1000"
    devices:
      - /dev/video10:/dev/video10
    restart: always

volumes:
    mysql-db:
        driver: local
