---
name: Deploy EPGStation
on:
  push:
    branches:
      - v2
    paths:
      - '.github/workflows/deploy-epgstation.yml'
      - 'docker-compose-epgstation.yml'
      - 'epgstation/**'
      - 'cron/**'

  workflow_run:
    workflows: ["docker push epgstation"]
    types:
      - completed

jobs:
  deploy:
    name: Auto Deploy via ssh
    runs-on: ubuntu-latest
    steps:
      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TS_EPGSTATION_HOST }}
          username: ${{ secrets.TS_EPGSTATION_USERNAME }}
          key: ${{ secrets.TS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            git clone https://github.com/miutaku/docker-mirakurun-epgstation-softcas.git
            cd docker-mirakurun-epgstation-softcas
            docker compose -f docker-compose-epgstation.yml down
            docker image rm -f ghcr.io/${{ github.actor }}/epgstation-miutaku-oci
            git checkout . && git checkout v2 && git pull origin v2
            sed -i 's/__MIRAKURUN_HOST__/${{ secrets.MIRAKURUN_HOST }}/g' epgstation/config/config.yml
            sed -i 's/__MIRAKURUN_PORT__/${{ secrets.MIRAKURUN_PORT }}/g' epgstation/config/config.yml
            sed -i 's/__MYSQL_HOST__/${{ secrets.TiDB_HOST }}/g' epgstation/config/config.yml
            sed -i 's/__MYSQL_PORT__/${{ secrets.TiDB_PORT }}/g' epgstation/config/config.yml
            sed -i 's/__MYSQL_USER__/${{ secrets.TiDB_USER }}/g' epgstation/config/config.yml
            sed -i 's/__MYSQL_PASSWORD__/${{ secrets.TiDB_PASSWORD }}/g' epgstation/config/config.yml
            sed -i 's|__NOTIFY_WEBHOOK__|${{ secrets.NOTIFY_WEBHOOK }}|g' epgstation/config/config.yml
            sed -i 's|__CRITICAL_WEBHOOK__|${{ secrets.CRITICAL_WEBHOOK }}|g' epgstation/config/config.yml
            sed -i 's/__CIFS_USER__/${{ secrets.CIFS_USER }}/g' docker-compose-epgstation.yml
            sed -i 's/__CIFS_PASSWORD__/${{ secrets.CIFS_PASSWORD }}/g' docker-compose-epgstation.yml
            sed -i 's/__CIFS_HOST__/${{ secrets.CIFS_HOST }}/g' docker-compose-epgstation.yml
            docker compose -f docker-compose-epgstation.yml up -d
