---
name: Deploy to OCI
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Auto Deploy via ssh
    runs-on: ubuntu-latest
    steps:
      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TS_SSH_HOST }}
          username: ${{ secrets.TS_SSH_USERNAME }}
          key: ${{ secrets.TS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/
            git clone https://github.com/miutaku/docker-mirakurun-epgstation-softcas.git
            cd docker-mirakurun-epgstation-softcas
            git checkout . && git checkout main
            sed -i 's/__MYSQL_HOST__/${{ secrets.HEATWAVE_HOST }}/g' epgstation/config/config.yml
            sed -i 's/__MYSQL_USER__/${{ secrets.HEATWAVE_USER }}/g' epgstation/config/config.yml
            sed -i 's/__MYSQL_PASSWORD__/${{ secrets.HEATWAVE_PASSWORD }}/g' epgstation/config/config.yml
            sed -i 's/__NFS_USER__/${{ secrets.NFS_USER }}/g' docker-compose-epgstation.yml
            sed -i 's/__NFS_PASSWORD__/${{ secrets.NFS_PASSWORD }}/g' docker-compose-epgstation.yml
            sed -i 's/__NFS_HOST__/${{ secrets.NFS_HOST }}/g' docker-compose-epgstation.yml
            docker compose -f docker-compose-epgstation.yml down
            git pull origin main
            docker compose -f docker-compose-epgstation.yml up -d
